import { useEffect, useState } from 'react'
import { Code2, Copy, FileText, Trash2 } from 'lucide-react'
import type { Article, ArticleLayout, LayoutPlatform } from '../../../shared/contracts'
import { Select } from '../components/Select'
import type { ToastState } from '../components/Toast'
import { useConfirm } from '../components/useConfirm'
import { errorMessage, formatDate, sanitizeHtml } from '../lib'

const platformNames:Record<LayoutPlatform,string>={wechat:'微信公众号',xiaohongshu:'小红书',web:'通用网页'}
export function LayoutsPage({ showToast }: { showToast(toast: ToastState): void }): React.JSX.Element { const [articles,setArticles]=useState<Article[]>([]);const [layouts,setLayouts]=useState<ArticleLayout[]>([]);const [articleId,setArticleId]=useState('');const [platform,setPlatform]=useState<LayoutPlatform>('wechat');const [selectedId,setSelectedId]=useState('');const [busy,setBusy]=useState(false);const selected=layouts.find(item=>item.id===selectedId)
  const refresh=async()=>{const [a,l]=await Promise.all([window.moliu.articles.list(),window.moliu.layouts.list()]);setArticles(a);setLayouts(l);setArticleId(x=>a.some(i=>i.id===x)?x:a[0]?.id??'');setSelectedId(x=>l.some(i=>i.id===x)?x:l[0]?.id??'')};useEffect(()=>{void refresh().catch(e=>showToast({type:'error',message:errorMessage(e)}))},[])
  const create=async()=>{if(!articleId)return;setBusy(true);try{const item=await window.moliu.layouts.create({articleId,platform});await refresh();setSelectedId(item.id);showToast({type:'success',message:'排版稿已生成'})}catch(e){showToast({type:'error',message:errorMessage(e)})}finally{setBusy(false)}};const copy=async(text:string,message:string)=>{await navigator.clipboard.writeText(text);showToast({type:'success',message})}
  return <div className="page layouts-page"><section className="page-intro"><div><span className="eyebrow">PUBLISH FORMATTER</span><h2>文章排版</h2></div></section><section className="layout-composer"><label className="field"><span>文章</span><Select value={articleId} onChange={setArticleId} ariaLabel="文章" options={articles.map(a=>({value:a.id,label:title(a)}))} /></label><label className="field"><span>平台</span><Select value={platform} onChange={(value)=>setPlatform(value as LayoutPlatform)} ariaLabel="平台" options={(Object.keys(platformNames) as LayoutPlatform[]).map(key=>({value:key,label:platformNames[key]}))} /></label><button className="button primary" disabled={busy||!articleId} onClick={()=>void create()}><FileText size={16}/>{busy?'正在排版…':'生成排版稿'}</button></section><section className="layout-workbench"><aside><header><span className="eyebrow">VERSIONS</span><h3>排版稿</h3></header>{layouts.filter(item=>item.articleId===articleId).map(item=><button key={item.id} className={item.id===selectedId?'active':''} onClick={()=>setSelectedId(item.id)}><strong>{platformNames[item.platform]}</strong><span>{item.articleVersionId.slice(0,8)} · {formatDate(item.createdAt)}</span></button>)}</aside><main>{selected?<LayoutPreview item={selected} onCopy={copy} onRemove={async()=>{await window.moliu.layouts.remove(selected.id);await refresh()}}/>:<div className="article-empty"><FileText size={28}/><h3>暂无排版稿</h3></div>}</main></section></div> }
function LayoutPreview({item,onCopy,onRemove}:{item:ArticleLayout;onCopy(text:string,message:string):Promise<void>;onRemove():Promise<void>}):React.JSX.Element{const {confirm,ConfirmPortal}=useConfirm();return <div className="layout-preview"><header><div><span className="eyebrow">{platformNames[item.platform]}</span><h3>{item.title}</h3><p>{item.articleStatusSnapshot==='draft'?'草稿版本':'已锁定版本'} · {formatDate(item.createdAt)}</p></div><button className="icon-button danger" title="删除排版稿" aria-label="删除排版稿" onClick={async()=>{if(await confirm({title:'删除排版稿？',message:'此操作不可撤销，关联的发布记录会保留但会标记为失效。',danger:true,confirmLabel:'删除'})){await onRemove()}}}><Trash2 size={16}/></button></header><div className="layout-actions"><button className="button secondary" onClick={()=>void onCopy(item.plainText,'发布文案已复制')}><Copy size={15}/>复制发布文案</button><button className="button ghost" onClick={()=>void onCopy(item.html,'网页源码已复制')}><Code2 size={15}/>复制网页源码</button></div><article className="layout-html" dangerouslySetInnerHTML={{__html: sanitizeHtml(item.html)}}/>{ConfirmPortal}</div>}
function title(article:Article):string{return article.rawMarkdown.match(/^#\s+(.+)$/m)?.[1]??'未命名文章'}
