import { useEffect, useMemo, useState } from 'react'
import { Check, Plus, Settings2, Sparkles } from 'lucide-react'
import type { Article, ProviderSummary, ReviewRole, ReviewTask } from '../../../shared/contracts'
import type { ToastState } from '../components/Toast'
import { errorMessage } from '../lib'

export function ReviewsPage({ providers, showToast }: { providers: ProviderSummary[]; showToast(toast: ToastState): void }): React.JSX.Element {
  const [articles, setArticles] = useState<Article[]>([]); const [roles, setRoles] = useState<ReviewRole[]>([]); const [tasks, setTasks] = useState<ReviewTask[]>([])
  const [articleId, setArticleId] = useState(''); const [selected, setSelected] = useState<Set<string>>(new Set()); const [target, setTarget] = useState(''); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false)
  const models = useMemo(() => providers.filter(p => p.enabled && p.hasApiKey).flatMap(p => p.models.filter(m => m.enabled).map(m => ({ p, m }))), [providers])
  const refresh = async () => { const [a, r, t] = await Promise.all([window.moliu.articles.list(), window.moliu.reviews.listRoles(), window.moliu.reviews.listTasks()]); setArticles(a); setRoles(r); setTasks(t); setArticleId(x => a.some(v => v.id === x) ? x : a[0]?.id ?? ''); setTarget(x => x || (models[0] ? JSON.stringify([models[0].p.id, models[0].m.modelId]) : '')) }
  useEffect(() => { void refresh().catch(e => showToast({ type: 'error', message: errorMessage(e) })) }, [])
  const model = () => { try { const [providerId, model] = JSON.parse(target); return { providerId, model } } catch { return null } }
  const start = async () => { const x = model(); if (!articleId || !selected.size || !x) return; setBusy(true); try { await window.moliu.reviews.start({ articleId, roleIds: [...selected], fallbackProviderId: x.providerId, fallbackModel: x.model }); await refresh(); showToast({ type: 'success', message: '评审完成' }) } catch (e) { showToast({ type: 'error', message: errorMessage(e) }) } finally { setBusy(false) } }
  const apply = async (task: ReviewTask) => { const x = model(); if (!x) return; setBusy(true); try { await window.moliu.reviews.apply(task.id, x.providerId, x.model); await refresh(); showToast({ type: 'success', message: '已生成改稿新版本' }) } catch (e) { showToast({ type: 'error', message: errorMessage(e) }) } finally { setBusy(false) } }
  return <div className="page reviews-page"><section className="page-intro"><div><span className="eyebrow">REVIEW STUDIO</span><h2>内容评审</h2><p>用多个专业视角审一遍成稿。</p></div><button className="button secondary" onClick={() => setOpen(true)}><Settings2 size={16}/>管理角色</button></section><section className="review-composer"><label className="field"><span>成稿</span><select value={articleId} onChange={e => setArticleId(e.target.value)}>{articles.map(a => <option key={a.id} value={a.id}>{a.rawMarkdown.match(/^#\s+(.+)$/m)?.[1] || 'Untitled'}</option>)}</select></label><label className="field"><span>模型</span><select value={target} onChange={e => setTarget(e.target.value)}>{models.map(({ p, m }) => <option key={m.id} value={JSON.stringify([p.id, m.modelId])}>{m.displayName}</option>)}</select></label><div className="review-role-options">{roles.map(r => <label key={r.id}><input type="checkbox" checked={selected.has(r.id)} onChange={e => setSelected(s => { const n = new Set(s); e.target.checked ? n.add(r.id) : n.delete(r.id); return n })}/>{r.name}</label>)}</div><button className="button primary" disabled={busy || !selected.size} onClick={() => void start()}><Sparkles size={16}/>开始评审</button></section><section className="review-results">{tasks.map(t => <article key={t.id}><header><strong>评审任务</strong><button className="button secondary compact" onClick={() => void apply(t)} disabled={busy}><Check size={14}/>应用改稿</button></header>{t.opinions.map(o => <div className="review-opinion" key={o.id}><h3>{o.roleName}</h3>{o.problems.map(p => <label key={p.id}><input type="checkbox" checked={p.adopted} onChange={async e => { await window.moliu.reviews.updateProblem({ ...p, adopted: e.target.checked }); await refresh() }}/><b>{p.position} · {p.severity}</b><span>{p.issue}<small>{p.suggestion}</small></span></label>)}</div>)}</article>)}</section>{open && <RoleDialog roles={roles} onClose={() => setOpen(false)} onSaved={async () => { setOpen(false); await refresh() }} showToast={showToast}/>}</div>
}

function RoleDialog({ roles, onClose, onSaved, showToast }: { roles: ReviewRole[]; onClose(): void; onSaved(): Promise<void>; showToast(toast: ToastState): void }): React.JSX.Element { const [name, setName] = useState(''); const [prompt, setPrompt] = useState('Please review the article. Return one <评审意见> block.'); return <div className="modal-overlay"><section className="framework-template-dialog"><h2>新建评审角色</h2><label className="field"><span>名称</span><input value={name} onChange={e => setName(e.target.value)}/></label><label className="field"><span>System prompt</span><textarea rows={6} value={prompt} onChange={e => setPrompt(e.target.value)}/></label><footer><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" onClick={async () => { try { await window.moliu.reviews.saveRole({ name, systemPrompt: prompt, extractionTag: '评审意见', extractionOccurrence: 'last', dimensions: [], sortOrder: roles.length }); await onSaved(); showToast({ type: 'success', message: '角色已保存' }) } catch (e) { showToast({ type: 'error', message: errorMessage(e) }) } }}><Plus size={15}/>保存</button></footer></section></div> }
