import { useEffect, useMemo, useState } from 'react'
import { Copy, Image, LoaderCircle, Sparkles, Trash2 } from 'lucide-react'
import type { Article, ProviderSummary, VisualPack, VisualPrompt } from '../../../shared/contracts'
import type { ToastState } from '../components/Toast'
import { useConfirm } from '../components/useConfirm'
import { errorMessage, formatDate } from '../lib'

export function VisualsPage({ providers, showToast }: { providers: ProviderSummary[]; showToast(toast: ToastState): void }): React.JSX.Element {
  const [articles, setArticles] = useState<Article[]>([]); const [packs, setPacks] = useState<VisualPack[]>([]); const [articleId, setArticleId] = useState(''); const [target, setTarget] = useState(''); const [count, setCount] = useState(3); const [busy, setBusy] = useState(false)
  const models = useMemo(() => providers.filter(p => p.enabled && p.hasApiKey).flatMap(p => p.models.filter(m => m.enabled).map(m => ({ p, m }))), [providers])
  const selected = articles.find(article => article.id === articleId)
  const refresh = async () => { const [nextArticles, nextPacks] = await Promise.all([window.moliu.articles.list(), window.moliu.visuals.list()]); setArticles(nextArticles); setPacks(nextPacks); setArticleId(current => nextArticles.some(a => a.id === current) ? current : nextArticles[0]?.id ?? ''); setTarget(current => current || (models[0] ? JSON.stringify([models[0].p.id, models[0].m.modelId]) : '')) }
  useEffect(() => { void refresh().catch(error => showToast({ type: 'error', message: errorMessage(error) })) }, [])
  const generate = async () => { try { const [providerId, model] = JSON.parse(target); if (!articleId || !providerId || !model) return; setBusy(true); await window.moliu.visuals.generate({ articleId, providerId, model, inlineCount: count }); await refresh(); showToast({ type: 'success', message: '配图三件套已生成' }) } catch (error) { showToast({ type: 'error', message: errorMessage(error) }) } finally { setBusy(false) } }
  const copy = async (text: string) => { await navigator.clipboard.writeText(text); showToast({ type: 'success', message: '提示词已复制' }) }
  const currentPacks = packs.filter(pack => pack.articleId === articleId)
  return <div className="page visuals-page"><section className="page-intro"><div><span className="eyebrow">VISUAL KIT</span><h2>配图三件套</h2><p>只生成可复用的视觉提示词，不直接消耗图像模型额度。</p></div></section><section className="visual-composer"><label className="field"><span>文章</span><select name="articleId" autoComplete="off" value={articleId} onChange={e => setArticleId(e.target.value)}>{articles.map(article => <option key={article.id} value={article.id}>{title(article)}</option>)}</select></label><label className="field"><span>文本模型</span><select name="modelTarget" autoComplete="off" value={target} onChange={e => setTarget(e.target.value)}>{models.map(({ p, m }) => <option key={m.id} value={JSON.stringify([p.id, m.modelId])}>{p.displayName} / {m.displayName}</option>)}</select></label><label className="field"><span>文内图数量</span><select name="inlineCount" autoComplete="off" value={count} onChange={e => setCount(Number(e.target.value))}>{[2, 3, 4, 5].map(value => <option key={value} value={value}>{value} 张</option>)}</select></label><button className="button primary" disabled={busy || !articleId || !target} onClick={() => void generate()}>{busy ? <LoaderCircle className="spin" size={16} /> : <Sparkles size={16} />}生成配图方案</button></section>{selected?.status === 'draft' && <p className="visual-warning">草稿警告：方案绑定当前文章版本；文章继续修改后，请重新生成以避免视觉与正文不一致。</p>}<section className="visual-results">{currentPacks.length ? currentPacks.map(pack => <VisualPackCard key={pack.id} pack={pack} onCopy={copy} onRemove={async () => { await window.moliu.visuals.remove(pack.id); await refresh() }} />) : <div className="article-empty"><Image size={28}/><h3>还没有配图方案</h3><p>选择一篇成稿后生成封面、文内配图和发布配图提示词。</p></div>}</section></div>
}

function VisualPackCard({ pack, onCopy, onRemove }: { pack: VisualPack; onCopy(text: string): Promise<void>; onRemove(): Promise<void> }): React.JSX.Element { const { confirm, ConfirmPortal } = useConfirm(); return <article className="visual-pack"><header><div><span className="eyebrow">ARTICLE VERSION</span><h3>{pack.articleVersionId.slice(0, 8)} · {pack.articleStatusSnapshot === 'draft' ? '草稿版本' : '已锁定版本'}</h3><p>{pack.model} · {formatDate(pack.createdAt)}</p></div><button className="icon-button danger" title="删除方案" aria-label="删除方案" onClick={async () => { if (await confirm({ title: '删除视觉方案？', message: '此操作不可撤销。', danger: true, confirmLabel: '删除' })) { await onRemove() } }}><Trash2 size={16}/></button></header><section className="visual-cover"><div><span>封面主视觉</span><strong>{pack.cover.visual}</strong><em>{pack.cover.overlayText}</em></div><Prompt value={pack.cover.prompt} onCopy={onCopy}/></section><PromptGroup title="文内配图" items={pack.inlineImages} onCopy={onCopy}/><PromptGroup title="发布配图" items={pack.releaseImages} onCopy={onCopy}/>{ConfirmPortal}</article> }
function PromptGroup({ title, items, onCopy }: { title: string; items: VisualPrompt[]; onCopy(text: string): Promise<void> }): React.JSX.Element { return <section className="visual-prompt-group"><h4>{title}</h4>{items.map((item, index) => <div className="visual-prompt" key={`${item.location}-${index}`}><header><strong>{item.location}</strong><span>{item.ratio} · {item.purpose}</span></header><Prompt value={item.prompt} onCopy={onCopy}/><small>替代文本：{item.alt}</small></div>)}</section> }
function Prompt({ value, onCopy }: { value: string; onCopy(text: string): Promise<void> }): React.JSX.Element { return <div className="visual-prompt-text"><p>{value}</p><button className="button ghost compact" onClick={() => void onCopy(value)}><Copy size={14}/>复制提示词</button></div> }
function title(article: Article): string { return article.rawMarkdown.match(/^#\s+(.+)$/m)?.[1] ?? '未命名文章' }
