import { createServer } from 'node:http'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { _electron as electron } from 'playwright-core'

const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const content=body.includes('中文内容视觉总监')?'<配图方案><封面><主视觉>一盏台灯照亮书桌</主视觉><封面文案>把复杂事讲明白</封面文案><提示词>editorial illustration, warm desk lamp, clean composition, soft light, ample negative space, no text, no watermark</提示词></封面><文内配图><图><位置>开头后</位置><用途>建立阅读情绪</用途><比例>16:9</比例><提示词>minimal editorial illustration, notebook and lamp, warm light, no text</提示词><替代文本>台灯与笔记本</替代文本></图></文内配图><发布配图><图><位置>公众号头图</位置><用途>公众号发布</用途><比例>2.35:1</比例><提示词>editorial cover, warm desk scene, no text</提示词><替代文本>温暖书桌封面</替代文本></图></发布配图></配图方案>':'# ok';res.setHeader('Content-Type','application/json');res.end(JSON.stringify({model:'visual-smoke',choices:[{message:{content}}]}))})
await new Promise(done=>server.listen(0,'127.0.0.1',done));const port=server.address().port;const root=await mkdtemp(join(tmpdir(),'moliu-visual-smoke-'));const executablePath=process.env.MOLIU_EXECUTABLE?resolve(process.env.MOLIU_EXECUTABLE):resolve('node_modules/electron/dist/electron.exe');const app=await electron.launch({executablePath,args:process.env.MOLIU_EXECUTABLE?[]:['.'],env:{...process.env,MOLIU_USER_DATA_DIR:root}})
try{const page=await app.firstWindow();await page.waitForLoadState('domcontentloaded');const data=await page.evaluate(async({port})=>{const provider=await window.moliu.providers.save({displayName:'Visual',protocol:'openai-compatible',baseUrl:`http://127.0.0.1:${port}/v1`,defaultModel:'visual-smoke',enabled:true,isRelay:false,capabilities:{chat:true,jsonMode:false,streaming:false,vision:false,image:false},models:[{modelId:'visual-smoke',displayName:'Visual',reasoningVariants:[],isDefault:true,enabled:true}],apiKey:'x'});const article=await window.moliu.articles.save({materialIds:[],manualOutline:'',status:'draft',rawMarkdown:'# 测试文章\n\n正文',source:'manual'});const pack=await window.moliu.visuals.generate({articleId:article.id,providerId:provider.id,model:'visual-smoke',inlineCount:1});const saved=await window.moliu.visuals.list(article.id);return {cover:pack.cover.prompt,inline:pack.inlineImages.length,release:pack.releaseImages.length,saved:saved.length,version:pack.articleVersionId===article.currentVersionId}}, {port});if(!data.cover||data.inline!==1||data.release!==1||data.saved!==1||!data.version)throw new Error('Visual workflow failed');console.log('Visual smoke passed')}finally{await app.close();await new Promise(done=>server.close(done));await rm(root,{recursive:true,force:true})}
