import { createServer } from 'node:http'
import { mkdir, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve, sep } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { _electron as electron } from 'playwright-core'
const server=createServer(async(req,res)=>{if(req.method!=='POST'||req.url!=='/v1/chat/completions')return res.writeHead(404).end();let body='';for await(const c of req)body+=c;const isReview=body.includes('审稿并使用');const content=isReview?'<评审意见>位置：开头｜严重程度：中｜问题：钩子偏弱｜建议：用反问强化冲突\n总体建议：强化开头。</评审意见>':'# 改稿标题\n\n这是改稿后的正文。';res.setHeader('Content-Type','application/json');res.end(JSON.stringify({model:'review-smoke',choices:[{message:{content}}]}))})
await new Promise(r=>server.listen(0,'127.0.0.1',r));const address=server.address();const root=resolve(tmpdir(),'moliu-review-smoke',String(Date.now()));const executablePath=process.env.MOLIU_EXECUTABLE?resolve(process.env.MOLIU_EXECUTABLE):resolve('node_modules/electron/dist/electron.exe');await mkdir(root,{recursive:true});const app=await electron.launch({executablePath,args:process.env.MOLIU_EXECUTABLE?[]:['.'],env:{...process.env,MOLIU_USER_DATA_DIR:root}})
try{const page=await app.firstWindow();await page.waitForLoadState('domcontentloaded');await page.getByRole('button',{name:'模型网关'}).first().click();await page.getByRole('button',{name:/空白配置/}).click();await page.getByLabel('显示名称').fill('Review');await page.getByLabel('Base URL').fill(`http://127.0.0.1:${address.port}/v1`);await page.locator('.provider-editor').getByLabel(/API Key/).fill('x');await page.getByLabel('显示别名').fill('Review');await page.getByLabel('API 模型 ID').fill('review-smoke');await page.locator('.provider-editor').getByRole('button',{name:'加密保存'}).click();await page.getByText('供应商配置已加密保存').waitFor();const data=await page.evaluate(async()=>{const p=(await window.moliu.providers.list())[0];const a=await window.moliu.articles.save({materialIds:[],manualOutline:'x',status:'draft',rawMarkdown:'# 原稿\n\n正文',source:'manual'});const role=await window.moliu.reviews.saveRole({name:'审稿人',systemPrompt:'审稿并使用 <评审意见> 输出',extractionTag:'评审意见',extractionOccurrence:'last',dimensions:['可读性'],sortOrder:0});const r=await window.moliu.reviews.start({articleId:a.id,roleIds:[role.id],fallbackProviderId:p.id,fallbackModel:'review-smoke'});const revised=await window.moliu.reviews.apply(r.task.id,p.id,'review-smoke');const task=await window.moliu.reviews.listTasks(a.id);return {opinions:r.task.opinions.length,problems:r.task.opinions[0]?.problems.length,markdown:revised.rawMarkdown,status:task[0]?.status}});if(data.opinions!==1||data.problems!==1||data.status!=='applied'||!data.markdown.includes('改稿标题'))throw new Error('Review workflow failed');console.log('Review smoke passed')}finally{await app.close();await new Promise(r=>server.close(r))}
const db=new DatabaseSync(resolve(root,'moliu.db'));const row=db.prepare('SELECT COUNT(*) count FROM review_tasks').get();db.close();if(row.count!==1)throw new Error('Review task not persisted');if(!root.startsWith(`${resolve(tmpdir(),'moliu-review-smoke')}${sep}`))throw new Error('Unexpected cleanup target');await rm(root,{recursive:true,force:true})
